### PR TITLE
docs: fix dead link

### PR DESCRIPTION
**Pull request by shawaj**
Fix dead link in docs page

Change-type: patch
Signed-off-by: Aaron Shaw <aaron@balena.io>

### CODE REVIEW

**Review by AlexProgrammerDE — CHANGES_REQUESTED** [review]
@shawaj i think that doesn't work... It looks like it worked perfectly before.

**Comment by shawaj** [comment]
@AlexProgrammerDE if you use it from GitHub it works, but if you try the link from the docs pages here... 
https://sound.balenalabs.io/docs/customization/

https://sound.balenalabs.io/docs/device-support/#recommended

It tries to take you to the following link which doesn't work as it has duplicated the docs part:
https://sound.balenalabs.io/docs/docs/usage#modes-of-operation

**Review by AlexProgrammerDE — APPROVED** [review]
Ok then

**Comment by shawaj** [comment]
@AlexProgrammerDE looking at this again, this actually isn't the only link with the same issue. A lot of the relative links on the docs have this same problem. 

I guess because on landr it has auto built the site to have the docs pages as directories. Whereas on GitHub they are files. 

Maybe there is a better way to handle this by some configuration change in landr or somewhere else, I'm not sure.

**Comment by AlexProgrammerDE** [comment]
@shawaj may you please contact the balena landr team then? Landr itself has some bugs and it would be nice if it was reported. I can't do it myself due to it going closed source for some time (i didn't check how it is now, but i assume it still is) and im not a official balena member with access.

**Comment by shawaj** [comment]
@AlexProgrammerDE sure thing! Will leave this unmerged for now as I think maybe landr needs to be able to handle relative links better perhaps.

For example the getting started page here:
https://sound.balenalabs.io/docs/

The link at the bottom under having trouble, point 1, gives an error.

However if you access the same page from here:
https://sound.balenalabs.io/docs/getting-started/

The same link works.

Anyway I'll see what can be done and report back 👌

**Comment by shawaj** [comment]
Closing this PR and will add any required changes to #393

**Pull request closed without merging**
