### PR TITLE
Add upnp

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
Change-type: minor

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by AlexProgrammerDE** [comment]
@chrisys this should work now.

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by tmigone** [comment]
Nice one, i'll give it a try soon!

**Comment by AlexProgrammerDE** [comment]
@tmigone what about this? It should work with BubbleUPnP.

**Comment by AlexProgrammerDE** [comment]
@chrisys why is the build failing? It should work.

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by AlexProgrammerDE** [comment]
@tmigone why is the build failing? Everything with my code should be fine. I really wish sometimes i had acces to the logs.

**Comment by tmigone** [comment]
@balena-ci retest

**Comment by tmigone** [comment]
@balena-ci retest as we were having problems with concourse recently

**Comment by borgmanJeremy** [comment]
Anything I can do to help with testing or getting this update merged to master? It would be helpful for my setup too.

**Comment by tmigone** [comment]
@AlexProgrammerDE is work here complete?

**Comment by AlexProgrammerDE** [comment]
@tmigone yes.

**Comment by tmigone** [comment]
awesome, going to check if my tv can do upnp and check it out. If not i guess i could download an app on my phone right? How were you testing it?

**Comment by AlexProgrammerDE** [comment]
@tmigone you have a android phone right? Use this upnp app to connet to the Pi: https://play.google.com/store/apps/details?id=com.bubblesoft.android.bubbleupnp

**Comment by AlexProgrammerDE** [comment]
@tmigone i think i should add some docs too. I had already added some, but they got deleted by landr. I will add them later.

**Comment by tmigone** [comment]
Yep, got android. Thanks! About docs yeah let's do it

**Comment by tmigone** [comment]
hey @AlexProgrammerDE this works great, good job! Committed a few minor changes.

Can you edit docs to include this and then squash commits? Then we can merge. Thanks again!

**Comment by AlexProgrammerDE** [comment]
@tmigone i will now work on the docs. Sorry for the delay. Im experimenting with [mineflayer](https://github.com/PrismarineJS/mineflayer) and [discord.js](https://discord.js.org/).

Btw did you know that you can configure your git so that it verifies your commits? I will do that now with all of commits.

**Comment by tmigone** [comment]
ohh discord.js looks nicee! new improvements coming to balena-minecraft? :D

> Btw did you know that you can configure your git so that it verifies your commits? I will do that now with all of commits.

I need to do that! Been wanting for ages but did not get to it lol.

**Comment by AlexProgrammerDE** [comment]
@tmigone discord.js is for discord bots. I use it for the bots on my discord servers. I think balena-minecraft is almost finished in its state. Everything works. The only problem is this "Corrupted jar file error". Idk why it still occurs. I already patched it. Btw a disadvantage of the auto verify is that you have to confirm your password on every signed commit. But you can also do unsigned commits. I love that system. It really improves the commit security.

**Comment by tmigone** [comment]
The password thing is annoying, but sounds reasonable. I'll try look into it soon, thanks

**Pull request merged**
