### PR TITLE
Check for bluetooth device

### PR DESCRIPTION
**Pull request by devdelay**
I need to use dtoverlay=pi3-disable-bt to disable bluetooth on some devices and leave it enabled on others. 

If bluetooth hardware is disabled, the bluetooth service will restart indefinitely.

There is probably a more eloquent way of doing this, but without adding any new env variables it makes sense to check if the bluetooth hardware exists before starting the service.

Connected to: #174 #177

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
@devdelay you can delete the bluetooth container from the docker compose file. Checking for the dtoverlay is a bad idea. Users with DACs wouldn't be able to use bluetooth with your code.

**Comment by devdelay** [comment]
If you delete bluetooth from docker compose file then no devices can have bluetooth. I need only a few of my devices to have bluetooth while others have it enabled.

**Comment by AlexProgrammerDE** [comment]
@devdelay you can directly push to devices (Not your whole application.). You can read more about it here: https://www.balena.io/docs/reference/balena-cli/#push-applicationordevice

**Comment by AlexProgrammerDE** [comment]
@devdelay yeah i just realized that the command is checking for bluetooth support and not for hardware settings. @tmigone do you think we should include this?

**Comment by tmigone** [comment]
@devdelay the check makes sense. Though I curious what is your use case? I understand your reasoning but not why you would disable bluetooth in some devices? Unless you are using a device that has no bluetooth hardware? 

Afaik, all the devices we support have bluetooth. Not to say there aren't others we'd like to support but don't have it.

**Comment by devdelay** [comment]
@tmigone Thanks, hardware check is a good idea even in case of failed hardware, user disabled bluetooth or a supported device that does not support bluetooth. Not sure which supported devices don't have bluetooth, maybe some Intel NUC?

I disable bluetooth on most of my devices because I don't want anyone to even see bluetooth as an option using the set device names. Those devices would otherwise just be RF spam that confuse users. Also, some devices that only use wifi like pi zero w get much better signal quality when bluetooth is disabled.

**Comment by AlexProgrammerDE** [comment]
The Pi 2 has no bluetoorh.

**Comment by AlexProgrammerDE** [comment]
@devdelay can you please follow our commits guidelines?  https://sound.balenalabs.io/contributing/

**Comment by tmigone** [comment]
@balena-ci rebase

**Comment by tmigone** [comment]
Closing this as #218 will provide a way of disabling bt on a per device basis without having to fiddle with the compose file

**Pull request closed without merging**
