### PR TITLE
Add Pimoroni Pirate Audio to list

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
Change-type: patch

@Fiqq90 does it work with this dtoverly value?

### CODE REVIEW

**Comment by chrisys** [comment]
@AlexProgrammerDE great thanks! Could you remove the link from the 'Yes' unless we have evidence of it working with balenaSound somewhere?

**Comment by AlexProgrammerDE** [comment]
@chrisys Fiqq90 did approve that it works: https://github.com/balenalabs/balena-sound/pull/125#pullrequestreview-381677899
But if you want it i will remove the link.

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by AlexProgrammerDE** [comment]
@chrisys can you do a squash merge?

**Comment by chrisys** [comment]
@AlexProgrammerDE no, versionbot doesn't like squash merges - you can squash it first and update the PR if you like?

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by AlexProgrammerDE** [comment]
@chrisys versionbot can parse squash commit. Works great in my own repo: https://github.com/AlexProgrammerDE/balena-minecraft-server
I use balena-versionist in a github ci workflow and i made many squash commits.

**Comment by chrisys** [comment]
@nazrhom did the approach regarding squash merges change? I know we have it turned off on all our repos for a reason but @AlexProgrammerDE is saying it works fine

**Comment by AlexProgrammerDE** [comment]
@nazrhom you can see my commits here: https://github.com/AlexProgrammerDE/balena-minecraft-server/commits/master
There are some squash commits.

**Pull request merged**
