### PR TITLE
adding RoonBridge support

### PR DESCRIPTION
**Pull request by magnu5**
Adding [RoonBridge](https://www.roonlabs.com) for Hi-Res Audio. Tested with USB DAC, Zorloo Ztella MQA.
Image based on balenalib/raspberrypi4-64-ubuntu and RoonBridge [installer](https://roonlabs.com/downloads) (modified to remove interactions).

### CODE REVIEW

**Comment by magnu5** [comment]
multi-room: Add multi-room feature
No breaking changes were made.

New services added:
- Roon Bridge

Change-type: minor
Signed-off-by: Magnus Tuominen <magnus.tuominen@outlook.com>

**Comment by AlexProgrammerDE** [comment]
@magnu5 This looks great! But to get this working with our CI please squash your commits and use the commit structure: https://sound.balenalabs.io/contributing/

**Comment by magnu5** [comment]
Thanks, I'll close this and submit a new pull request later today.

**Comment by AlexProgrammerDE** [comment]
@magnu5 theres no need for closing this PR. For a recheck just run: `@balena-ci retest`

**Comment by magnu5** [comment]
@balena-ci retest

**Comment by AlexProgrammerDE** [comment]
@magnu5 Ypu need some more steps to get this working with our CI. Please squash your commits and use the commit structure as described here: https://sound.balenalabs.io/contributing

**Comment by magnu5** [comment]
I though I did, the instructions are not very clear.

**Comment by magnu5** [comment]
cannot complete git rebase -i master, nothing is accepted.

**Comment by AlexProgrammerDE** [comment]
@magnu5 what did you write into the rebase text?

**Comment by magnu5** [comment]
What am I supposed to write? I tried every option listed, but all I get is missing arguments or could not parse or some other error

**Comment by AlexProgrammerDE** [comment]
@magnu5 i think ypu should write `pick` on one commit and write `squash` to all your commit, which shiuld be squashed into the one commit. Can ypu do that and give me the file before saving? I will check if its correct.

**Comment by magnu5** [comment]
@AlexProgrammerDE  git-rebase-todo:

```
pick 3a2868d
squash eb75099
#
# Commands:
# p, pick <commit> = use commit
# r, reword <commit> = use commit, but edit the commit message
# e, edit <commit> = use commit, but stop for amending
# s, squash <commit> = use commit, but meld into previous commit
# f, fixup <commit> = like "squash", but discard this commit's log message
# x, exec <command> = run command (the rest of the line) using shell
# b, break = stop here (continue rebase later with 'git rebase --continue')
# d, drop <commit> = remove commit
# l, label <label> = label current HEAD with a name
# t, reset <label> = reset HEAD to a label
# m, merge [-C <commit> | -c <commit>] <label> [# <oneline>]
# .       create a merge commit using the original merge commit's
# .       message (or the oneline, if no original merge commit was
# .       specified). Use -c <commit> to reword the commit message.
#
# These lines can be re-ordered; they are executed from top to bottom.
#
# If you remove a line here THAT COMMIT WILL BE LOST.
#
# You are editing the todo file of an ongoing interactive rebase.
# To continue rebase after editing, run:
#     git rebase --continue
#
```

**Comment by AlexProgrammerDE** [comment]
@magnu5 hm. You only get this two commits? What happens if you confirm it?

**Comment by AlexProgrammerDE** [comment]
@tmigone can you help here please?

**Comment by magnu5** [comment]
`balena-sound git:(3a2868d) git push --force-with-lease origin master
Everything up-to-date

➜  balena-sound git:(3a2868d) git push --force-with-lease origin 3a2868d
fatal: 3a2868d cannot be resolved to branch
➜  balena-sound git:(3a2868d)`

I am not used to working with branches, which one of those is to correct one?

**Comment by tmigone** [comment]
Closing due to inactivity. We should look into adapting it to 3.0 architecture if there is enough demand.

**Pull request closed without merging**
