### PR TITLE
add -M to amixer to fix volume mapping issues #117

### PR DESCRIPTION
**Pull request by MatthewCroughan**
Change-type: patch

Details of this are in the following issue comment. 

https://github.com/balenalabs/balena-sound/issues/117#issuecomment-609097464

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by AlexProgrammerDE** [comment]
@MatthewCroughan seems like something is here wrong can you try please to run the following commands?

1. Run `git clone https://github.com/MatthewCroughan/balena-sound.git --single-branch --branch MatthewCroughan:fix-amixer-volume-#117`
2. Run: `cd balena-sound`
3. Run: `git reset HEAD~3`
4. Run: `git add .`
5. Run: `git commit --amend`
6. Save the file how it is.
7. Run: `git push -f https://github.com/MatthewCroughan/balena-sound.git MatthewCroughan:fix-amixer-volume-#117`

**Comment by AlexProgrammerDE** [comment]
@tmigone does this PR fix your issue?

**Comment by MatthewCroughan** [comment]
I've done as you requested, though I don't actually understand what the problem is, so I'm running blind.

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by AlexProgrammerDE** [comment]
@MatthewCroughan the PR checks are failing. I dont know why.

**Comment by MatthewCroughan** [comment]
I was thinking there'd be a problem with running HEAD~3 since that puts me a few commits before, so I'll be overwriting previous work. But it is what you have requested, so I have done it.

**Comment by AlexProgrammerDE** [comment]
@MatthewCroughan seems like something is here wrong can you try please to run the following commands?

1. Run `git clone https://github.com/MatthewCroughan/balena-sound.git --single-branch --branch fix-amixer-volume-#117`
2. Run: `cd balena-sound`
3. Run: `git reset HEAD~1`
4. Run: `git add .`
5. Run: `git commit --amend`
6. The file should be saved like this:
> add -M to amixer to fix volume mapping issues #117
> 
>Change-type: patch
7. Run: `git push -f https://github.com/MatthewCroughan/balena-sound.git fix-amixer-volume-#117`

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by AlexProgrammerDE** [comment]
@MatthewCroughan sorry, but i have no idea what is causing the failure here. @chrisys can you help here?

**Comment by AlexProgrammerDE** [comment]
@MatthewCroughan can you try this again?

1. Run `git clone https://github.com/MatthewCroughan/balena-sound.git --single-branch --branch fix-amixer-volume-#117`
2. Run: `cd balena-sound`
3. Run: `git reset HEAD~1`
4. Run: `git add .`
5. Run: `git commit --amend`
6. The file should be saved like this:
> add -M to amixer to fix volume mapping issues #117
> 
>Change-type: patch
7. Run: `git push -f https://github.com/MatthewCroughan/balena-sound.git fix-amixer-volume-#117`

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by AlexProgrammerDE** [comment]
@MatthewCroughan sorry. It must be annoying for you, but can you do this comment again and the n **not** update your branch.

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by MatthewCroughan** [comment]
@AlexProgrammerDE What I'm more annoyed about is that the commit no longer includes my actual changes, but includes changes from other people. I'm really confused about this. Have we not just defeated the purpose of git by including so many commits from other people? It's interesting to see CI cause so much trouble for such a simple change, without any feedback as to why it's happening.

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by MatthewCroughan** [comment]
Any feedback?

**Comment by AlexProgrammerDE** [comment]
@MatthewCroughan i am confused like you. @tmigone can you please help us?

**Comment by tmigone** [comment]
Hey @MatthewCroughan, @AlexProgrammerDE, taking a look at this.
Our CI indeed is not very clear in communicating errors when something does not go as required, specially if you don't have access to the CI server to check the logs. Your point on lack of feedback being frustrating is super valid, we've been working on internally on improving this, thank you for letting us know. Also, we are in the process of revamping the contributing docs so that should improve too.

On to the problem here, I don't fully understand how the PR got into the state it's in, must be a combination of force pushes from both of you? My suggestion is that we take the lazy way out here, create a new PR and close this one. That would ensure a clean state and that commits are attributed to their authors too. Otherwise we could spend more time than what it's worth it. Let me know if this works for you and if you have any other questions! Thanks again for the contribution!

Here is how your commits should look like generally:
```
single line commit title, MANDATORY, usually "module: change explanation"

detailed description (OPTIONAL, can be multi line)

Change-type: major | minor | patch (MANDATORY, at least once in all of your PR commits)
Signed-off-by: Tomás Migone <tomas@balena.io> (OPTIONAL)
```

Note that new lines and order of elements ARE important. Change-type for instance requires a new line on top of it.

Looks like this if running `git log`:
```
commit 3e3a65eeb91abf0cd730e7899978a86eaec23d87
Author: Tomás Migone <tomas@balena.io>
Date:   Fri Jan 10 09:57:17 2020 -0300

    multi-room: Add multi-room feature
    
    This feature adds multi-room audio streaming to balenaSound.
    No breaking changes were made, but considering this a major version bump since it's a big feature and all services were affected.
    
    New services added:
    - snapcast-server
    - snapcast-client
    - fleet-supervisor
    
    - By default, all audio services now stream to a fifo pipe file instead of alsa backend.
    - Multi-room can be disabled via env var DISABLE_MULTI_ROOM.
    
    Change-type: major
    Signed-off-by: Tomás Migone <tomas@balena.io>
```

**Pull request closed without merging**
