### PR TITLE
Set the UUID to differentiate between instances

### PR DESCRIPTION
**Pull request by JodyGoldberg**
[https://github.com/balenalabs/balena-sound/issues/380](https://github.com/balenalabs/balena-sound/issues/380)

### CODE REVIEW

**Comment by shawaj** [comment]
@JodyGoldberg thanks for the PR. I can't comment on whether it'll be accepted or not from a code basis, however you'd need to fix the commit message to follow the contributing guidelines https://github.com/balenalabs/balena-sound/blob/master/CONTRIBUTING.md

Basically you will need to add the title, Change-type and Signed-off-by lines

**Comment by JodyGoldberg** [comment]
Thx, commit message updated.
generate version is still failing.   I'll read more docs to see what I missed.

**Comment by shawaj** [comment]
@JodyGoldberg I think if you change the title to:
`upnp: Set UUID to differentiate between instances`

And change signed-off-by to include your name and email:

`Signed-off-by: First Last <email@email.com>`

**Comment by shawaj** [comment]
@JodyGoldberg thanks! looks like the checks are passing now. Just need someone to review it now!

**Review by tmigone — APPROVED** [review]
Looks good! Thanks @JodyGoldberg for the contribution!

**Pull request merged**
