### PR TITLE
docs: Fix some formatting in ARCHITECTURE.md

### PR DESCRIPTION
**Pull request by doronbehar**
Change-type: minor

### CODE REVIEW

**Comment by doronbehar** [comment]
Automatically?? Just like that?

**Comment by AlexProgrammerDE** [comment]
Weird i thought it requires a review

**Comment by phil-d-wilson** [comment]
I think it's because your making changes in a branch, not Master. @tmigone ?!?

**Comment by tmigone** [comment]
Oh how nasty of bulldozer bot. I reckon this is a bug going to ask the CI guys.

**Pull request merged**
