### PR TITLE
add -M to amixer to fix volume mapping issues #117

### PR DESCRIPTION
**Pull request by MatthewCroughan**
Change-type: patch

Details of this are in the following issue comment. 

https://github.com/balenalabs/balena-sound/issues/117#issuecomment-609097464

### CODE REVIEW

**Comment by MatthewCroughan** [comment]
Is the failure here simply because I renamed the branch and a retest must be performed?

**Comment by AlexProgrammerDE** [comment]
@MatthewCroughan @tmigone is it maybe the `#` in the PR title or in the commit?

**Comment by tmigone** [comment]
What is failing? I'm confused now lol. I see all checks green :)

**Comment by AlexProgrammerDE** [comment]
@tmigone it just jumped from failing to passed. Very confusing.

**Comment by MatthewCroughan** [comment]
Perhaps some form of caching. It didn't last long. Phew.

**Comment by tmigone** [comment]
CI is mysterious! THANKS again for having to create 3 PR's for this.

**Comment by MatthewCroughan** [comment]
Well I was initially annoyed. Then when you came in with the explanation I started having fun. So no worries there 😅

**Pull request merged**
