### PR TITLE
Disable Bluetooth with an environment variable

### PR DESCRIPTION
**Pull request by VincentChalnot**
bluetooth-audio: Disable Bluetooth with an environment variable

As proposed in #196, allow the end user to toggle bluetooth support from the web management interface without having to fork the project, edit the docker-compose.yml, re-deploy the app from a different repository and manually updating the forked repository with this master regularily.

Connects-to: #196
Change-type: minor

### CODE REVIEW

**Comment by VincentChalnot** [comment]
As mentioned in #196, this behavior would not be needed if bluetooth-audio wasn't interfering with spotify-connect performances.
Test-case with Raspberry 3A+:
- Bluetooth-audio on, stuttering sound when using spotify
- Bluetooth-audio off, spotify works without any sound-related issue.

**Comment by tmigone** [comment]
@balena-ci rebase

**Comment by tmigone** [comment]
@balena-ci retest

**Comment by tmigone** [comment]
@VincentChalnot this looks good. Can you rebase your branch with the current master? I'll merge once that's done

**Comment by VincentChalnot** [comment]
@tmigone done!

**Comment by tmigone** [comment]
@balena-ci retest

**Comment by tmigone** [comment]
Hey @VincentChalnot, can you run the following commands? This is to rebase your PR into master rather than merge master back to your PR which is what you've done. Both approaches work, but merging back master produces an additional commit message which tends to clutter the commit history in the long run.

```
git remote add upstream https://github.com/balenalabs/balena-sound.git
git fetch upstream 
git checkout patch-1
git rebase upstream/master
git push --force-with-lease
```

Also, for our versioning we require some special commands on the commit message, `Change-type: patch` notably is missing in yours. You can read details here: https://sound.balenalabs.io/contributing/ But the gist of it:

```
git rebase -i HEAD~1
*replace pick with reword*
Add the Change-type: patch
git push --force-with-lease
```

**Comment by tmigone** [comment]
This is how the output of `git log` should look like:

```
commit 991e3fa326b095d3a9e7ca912b7a9b8a63c25bbb (HEAD -> patch-1)
Author: Vincent Chalnot <VincentChalnot@users.noreply.github.com>
Date:   Mon Jun 15 16:24:52 2020 +0200

    Disable Bluetooth with an environment variable
    
    As proposed in #196, allow the end user to disable bluetooth completely without having to fork the project, edit the docker-compose.yml and re-deploy the app from a different repository.
    
    Change-type: patch

commit 9625ac6848f215e0cf582299c0adfba145635118 (tag: v2.4.4, upstream/master, master)
Author: Balena CI <34882892+balena-ci@users.noreply.github.com>
Date:   Fri Jul 17 23:13:09 2020 +0300

    v2.4.4

commit e14c4d4c511ae69c0efc41b11e8f215da2c9ea43
Merge: 0d236c7 6eebb0b
Author: bulldozer-balena[bot] <62422113+bulldozer-balena[bot]@users.noreply.github.com>
Date:   Fri Jul 17 20:11:12 2020 +0000

    Merge pull request #237 from balenalabs/220-disable-multiroom-pi2
    
    multi-room: disable feature for raspberrypi2 fam

commit 6eebb0b756588d5c260d28ade9851c85e6c219e3
Author: Tomás Migone <tomas@balena.io>
Date:   Fri Jul 17 14:49:33 2020 -0300

    multi-room: disable feature for raspberrypi2 fam
    
    Connects-to: #220
    Change-type: patch
    Signed-off-by: Tomás Migone <tomas@balena.io>
```

Notice your single commit after v2.4.4 with the `Change-type: patch` tag

**Comment by tmigone** [comment]
Closing this since as of balenaSound 3.0 we have an env var for each audio plugin. See https://sound.balenalabs.io/docs/customization#plugins.

`SOUND_DISABLE_BLUETOOTH` should do the trick. Thanks!

**Pull request closed without merging**
