### PR TITLE
[WIP] Docs and 3D designs for a DIY balenaSound device (portable option too)

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
Init commit. 

Change-type: minor

Features to include: 
- [ ] Provide 3D models (#184) 
- [ ] Provide guides (@chrisys we could add some things from the boombeastic wiki: https://github.com/balenalabs/boombeastic/wiki)
- [ ] Add GPIO on/off option
- [ ] Add gpio remote control. (Reference this way: https://user-images.githubusercontent.com/40795980/74084516-32f60d00-4a70-11ea-9bfe-1eda369ade29.jpg) (#101) 
- [ ] Battery

**For the team:** You can add ideas via editining this comment. I hope this will get great. 👍

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
Do we really need a LED matrix? I think this would only add extra cost and use much energy.

**Comment by AlexProgrammerDE** [comment]
@curcuz could you please update the 3D designs? And add the Pi 4?

**Comment by curcuz** [comment]
@AlexProgrammerDE mind sharing some context?

**Comment by AlexProgrammerDE** [comment]
@curcuz yeah sorry. I had the idea to make balenaSound portable like boombeastic. You made some cool designs, but they are outdated. Can you replace the logo and fill the ledmatrix hole?

**Comment by AlexProgrammerDE** [comment]
may do this another time. we should concentrate on 3.0 support and bug fixes

**Pull request closed without merging**
