### PR TITLE
Add IQaudIO Pi-DAC+ to configuration table

### PR DESCRIPTION
**Pull request by michaellwilks**
Change-type: patch

Update DAC configuration table to include the IQaudIO Pi-DAC+, which works using dtoverlay value iqaudio-dacplus

### Hey there, appreciated contributor!

Have you taken a look at the [contribution guidelines](../CONTRIBUTING.md) for this project? To enable our CI to work correctly and version the releases of the project, you need to ensure your commit messages contain the required information [detailed here](../CONTRIBUTING.md). Thank you!

### CODE REVIEW

**Comment by chrisys** [comment]
Hey @michaellwilks this is great, thanks! You'll need to update the git commit message to include the change type footer (not the Github comment), then the CI will pass and we can merge this

**Comment by chrisys** [comment]
We'll need to bump the number to 13 now, too

**Comment by tmigone** [comment]
Glad it worked Mikey! 
I fixed the indexes.

**Comment by tmigone** [comment]
@balena-ci retest

**Pull request merged**
