### PR TITLE
Update README.md

### LINKED ISSUE #292: Link points to itself in docs
**Describe the problem**
Recursive link in README

**To Reproduce**
1. Go to README
2. Under Documentation, click docs

**Expected behavior**
Link should point to https://sound.balenalabs.io/docs/

**Screenshots**
https://i.imgur.com/264vLP8.png

**Additional context**
Forum ticket

### PR DESCRIPTION
**Pull request by anujdeshpande**
Fixes #292

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
@anujdeshpande hi! Can you please format the commit correctly so the CI builds a version? And can you also link the logo to the main website? (https://sound.balenalabs.io)

**Comment by anujdeshpande** [comment]
@AlexProgrammerDE Not sure what you mean by the logo thing

**Comment by AlexProgrammerDE** [comment]
@anujdeshpande `[logo](a link)` will make a image that opens a url when clicking the image.

**Comment by anujdeshpande** [comment]
@AlexProgrammerDE do we need a logo for link to the docs in the text body?

**Comment by tmigone** [comment]
Let's add the logo URL in the other PR.

**Review by tmigone — APPROVED** [review]

**Pull request merged**
