### PR TITLE
Documentation: added clear links to help on the Getting Started page

### PR DESCRIPTION
**Pull request by ChestersGarage**
Connects-to: #307
Change-type: patch
Signed-off-by: Mark Chester <mark@chesterfamily.org>

Placed a section at the bottom of the Getting Started page that links clearly to all support options.

### CODE REVIEW

**Comment by tmigone** [comment]
@balena-ci reabase

**Comment by tmigone** [comment]
damn you bot!!!
@balena-ci rebase

**Comment by tmigone** [comment]
@balena-ci rebase

**Comment by tmigone** [comment]
@balena-ci rebase

**Comment by tmigone** [comment]
Hey @ChestersGarage, I finally figured out. 
Before merging we need to get the latest master changes into your branch. We try not to use the `Update branch` button here to avoid adding unnecessary commits to the commit history. So we can achieve the same doing a rebase. I tried to use our bot, but forgot since the branch we are merging is not part of this repo the bot won't work. 

Long story short... here are the steps to rebase, assuming the changes on your fork happened in your own `master` branch:

```
git remote add upstream https://github.com/balenalabs/balena-sound.git
git fetch upstream
git rebase upstream/master
git push origin master --force
```

Let me know if this doesn't make sense. I'll be sure to add this to our contributors guides.

**Comment by ChestersGarage** [comment]
@tmigone, I updated and rebased from upstream as described.  Looks like it settled in OK.

**Review by tmigone — APPROVED** [review]

**Comment by tmigone** [comment]
Awesome. Thanks again for contributing!!

**Comment by tmigone** [comment]
@balena-ci retest

**Pull request merged**
