### PR TITLE
add -M to amixer to fix volume mapping issues #117

### PR DESCRIPTION
**Pull request by MatthewCroughan**
Change-type: patch

Details of this are in the following issue comment. 

https://github.com/balenalabs/balena-sound/issues/117#issuecomment-609097464

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
@tmigone it is failing again.

**Comment by tmigone** [comment]
Right... so this is a failure I haven't seen before. I suspect this might be because of the # on the branch name because I'm seeing a "Branch does not exist error", but I'll contact the mantainer of our ci tool to see if he can figure it out.

**Comment by MatthewCroughan** [comment]
Elated to know I'm breaking things hard :)

**Comment by tmigone** [comment]
> Elated to know I'm breaking things hard :)

Yes, thank you for that! It looks like indeed you broke our CI ;) There is an http request that the CI makes internally to the following URL: 
- https://api.github.com/repos/MatthewCroughan/balena-sound/branches/fix-amixer-volume-#117

Since the `#` is not url escaped (because our CI doesn't do that) that request fails, and the CI check fails! What the CI should be doing is escaping that URL to:
- https://api.github.com/repos/MatthewCroughan/balena-sound/branches/fix-amixer-volume-%23117

Apparently you are the first one using our CI and a `#` on the branch name! I've raised this issue internally in our CI repo so we can fix it. Now, you could wait till that is fixed (uncertain timeline really, could be tomorrow or a few days out) or move your changes to a renamed branch, and resubmit the PR (maybe you can rename the branch and avoid having to create a new PR). I know this is far from optimal and it's already been stupid amounts of work to get this merged, I feel you. Hopefully we can improve this process soon.

**Comment by MatthewCroughan** [comment]
Cannot quite figure out how to rename a branch in this manner. So am just going to submit a new PR. 

https://linuxize.com/post/how-to-rename-local-and-remote-git-branch/

**Pull request closed without merging**
