### PR TITLE
WIP: Add Troubleshooting

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
Change-type: patch

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
@chrisys do you have some things to add here?

**Comment by chrisys** [comment]
@AlexProgrammerDE great start! This is good information to add. I wanted to just highlight that @tmigone has been working on restructuring the docs in the `landr` branch. This will enable us to use [Landr](https://github.com/product-os/landr) to automatically build us a website for balenaSound (to go on something like sound.balenalabs.io). Here's an example of an early test: https://balena-sound-preview-landr.netlify.com/

@tmigone are you planning to PR the `landr` branch soon? Could we include a troubleshooting doc as Alex has started here?

**Comment by tmigone** [comment]
@chrisys @AlexProgrammerDE, nice work Alex, I think i can definitely add the troubleshooting section to the landr landing page for sound. I was planning on doing all the pending work on sound tomorrow (I know i have some PR's to review hehe).

So I think we can merge this PR as is and then tomorrow I pull from it into my PR.

**Comment by tmigone** [comment]
hey @AlexProgrammerDE, I'll merge this PR into `landr` branch so we can keep working on it there.

**Pull request merged**
