### PR TITLE
meta: Use balenablocks images instead of balenaplayground

### PR DESCRIPTION
**Pull request by tmigone**
Use production images at `balenablocks` dockerhub org.

Change-type: patch
Signed-off-by: Tomás Migone <tomas@balena.io>

### CODE REVIEW

**Comment by tmigone** [comment]
@balena-ci I self-certify!

**Comment by AlexProgrammerDE** [comment]
i just wanted to approve and i realized the CI can do that. Would that not be a security risk if users can do this command?

**Comment by tmigone** [comment]
I think you need to be part of the balenalabs org for the CI to approve on your behalf. You might be able to do it because of your contributor status, but regular users can't.

**Comment by tmigone** [comment]
Usually docs changes and simple stuff feel free to approve this way. For more complex changes we should still have at least someone else review before approve/merge.

**Pull request merged**
