### PR TITLE
Add --hostID arg to Snapcast client startup

### PR DESCRIPTION
**Pull request by ChestersGarage**
Change-type: patch
Signed-off-by: Mark Chester <mark@chesterfamily.org>
Connects-to: #332

### CODE REVIEW

**Review by tmigone — CHANGES_REQUESTED** [review]
Looks good, can you rebase @ChestersGarage to get latest changes? Thanks!

**Comment by ChestersGarage** [comment]
Rebased and pushed.

**Comment by ChestersGarage** [comment]
@tmigone  Any idea when this might get merged?  I did a bonehead move and created the PR from my master branch.  And it's holding me up from doing other things until this gets merged or rejected.

**Comment by ChestersGarage** [comment]
Can we please either merge or reject this so I can get on with my life?  ;)

**Comment by tmigone** [comment]
Hey @ChestersGarage, I'm back at it! Sorry it took so long, I can relate to the bonehead move as I'm guilty of that myself too haha. Looks like we need another rebase and I'll merge. I'll keep an extra eye out to do it ASAP.

**Comment by ChestersGarage** [comment]
Good to have you back, @tmigone!  Rebased and pushed.  Please merge at your convenience.  Thanks!

**Review by tmigone — APPROVED** [review]
Thanks :)

Approved!

**Pull request merged**
