### PR TITLE
Update 03-customization.md

### PR DESCRIPTION
**Pull request by ViciousCupcake**
Change-type: patch

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
@ViciousCupcake could you please make a amend commit and replace `fixed typo` with: `Change-type: patch` Our CI won't allow merging till it is fixed.

**Comment by ViciousCupcake** [comment]
Done

**Comment by AlexProgrammerDE** [comment]
@ViciousCupcake i think you forgot to push the changes

**Comment by AlexProgrammerDE** [comment]
Closing due to inactivity.

**Pull request closed without merging**
