### PR TITLE
Change device name variable

### PR DESCRIPTION
**Pull request by AlexProgrammerDE**
Change-type: patch

The variable is not only for bluetooth.

### CODE REVIEW

**Comment by AlexProgrammerDE** [comment]
@balena-ci retest

**Comment by tmigone** [comment]
I'm a bit late to the party, but I think we are "breaking" functionality here for folks that are using `BLUETOOTH_DEVICE_NAME` and update, right?

I can think of two fixes:

1) Update the version to reflect this is a breaking change, so change it to major and thus making this v3.0.0. This seems completely overkill though.
2) Add compatibility to it. So have `DEVICE_NAME` consider `BLUETOOTH_DEVICE_NAME` as a valid input also? We could then remove this on the next major change.

wdyt @chrisys @AlexProgrammerDE

**Comment by chrisys** [comment]
@tmigone you are totally right, option 2 seems valid to me

**Comment by AlexProgrammerDE** [comment]
@tmigone i will open a PR.

**Comment by tmigone** [comment]
Awesome, sorry i didn't get to this earlier

**Pull request merged**
